//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileLogistics.Web.modules {
    
    
    public partial class Default {
        
        /// <summary>
        /// divMiniTopStats control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMiniTopStats;
        
        /// <summary>
        /// htmlDashboard_MiniTopStats_OpeningJobs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl htmlDashboard_MiniTopStats_OpeningJobs;
        
        /// <summary>
        /// htmlDashboard_MiniTopStats_FinishedJobs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl htmlDashboard_MiniTopStats_FinishedJobs;
        
        /// <summary>
        /// htmlDashboard_MiniTopStats_TotalJobs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl htmlDashboard_MiniTopStats_TotalJobs;
        
        /// <summary>
        /// htmlDashboard_MiniTopStats_TotalCustomers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl htmlDashboard_MiniTopStats_TotalCustomers;
    }
}
